variables:
  IMAGE_NAME: "devsecops-demo-nana"
  IMAGE_TAG: "juice-shop-1.1"

stages:
  - test
  - build

yarn_test:
  image: node:18-bullseye
  stage: test
  script:
    - yarn install
    - yarn test

build_image:
  stage: build
  image: docker:24
  services:
    - docker:24-dind
  variables:
    DOCKER_PASS: "Ilovebabouantou237#"
    DOCKER_USER: "nicoleketch"
  before_script:
    # provides login credentials for dockerhub account
    - echo docker login -u $DOCKER_USER --password-stdin $DOCKER_PASS docker.io
  script:
    # cloned initial image to my personal account 
    - docker build -t $DOCKER_USER/$IMAGE_NAME:$IMAGE_TAG .
    - docker push $DOCKER_USER/$IMAGE_NAME:$IMAGE_TAG